### ISSUE TITLE
Control Panel: Translation tool - click on wrench 

### ISSUE THREAD

**Issue by hartenthaler** [jon48/webtrees-mod-translationtool#6]
There is an error message when I try to show the options menu for the Translation Tool in the control panel. But I'm not sure to use the latest version of your webtrees package.

Composer could not find the config file: …/app/../composer.json
To initialize a project, please create a composer.json file. See https\://getcomposer.org/basic-usage …/vendor/composer/composer/src/Composer/Factory.php:309
#0 …/vendor/composer/composer/src/Composer/Factory.php(618): Composer\Factory->createComposer()
#&#x2060;1 …/modules_v4/myartjaub_translationtool/app/Services/ComposerService.php(62): Composer\Factory::create()
#&#x2060;2 …/modules_v4/myartjaub_translationtool/app/Services/SourceCodeService.php(66): MyArtJaub\Webtrees\Module\TranslationTool\Services\ComposerService->listMyArtJaubPackagesPaths()
#&#x2060;3 …/modules_v4/myartjaub_translationtool/app/Http/RequestHandlers/TranslationStatus.php(66): MyArtJaub\Webtrees\Module\TranslationTool\Services\SourceCodeService->sourceCodePaths()

**Comment by jon48** [comment]
Indeed, I have actually not correctly covered the case when the Translation tool is provided as part of the full package...

This is actually more of a development utility to identify missing translations in my modules, and I am only using it my dev environments where I have a composer.json file at the root (the module is actually disabled by default).

I will address this use case (the module will not be able to detect all missing translations without loading the composer.json, but again, it is not used in its intended environment when running on a live environment), but I might remove it from the packaged version as well to avoid confusion.
